services:
  postgres:
    image: zulfifazhar/light-postgres:latest
    container_name: light_postgres
    environment:
      POSTGRES_USER: light_postgres
      POSTGRES_PASSWORD: light_postgres_root
    ports:
      - "5452:5432"
    restart: unless-stopped
