"""create suksesor table

Revision ID: 0962dfbc80ce
Revises:
Create Date: 2026-04-14 22:26:06.706593

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0962dfbc80ce"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suksesor",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("nip", sa.String(length=20), nullable=False),
        sa.Column("nama", sa.String(length=255), nullable=False),
        sa.Column("unit_kerja", sa.String(length=255), nullable=True),
        sa.Column("grade", sa.String(length=5), nullable=True),
        sa.Column("kompetensi", sa.Text(), nullable=True),
        sa.Column("potensi", sa.String(length=20), nullable=True),
        sa.Column("readiness", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suksesor_nip"), "suksesor", ["nip"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_suksesor_nip"), table_name="suksesor")
    op.drop_table("suksesor")
    # ### end Alembic commands ###
