"""add matching_history table

Revision ID: 76c30486c443
Revises: 0962dfbc80ce
Create Date: 2026-04-15 20:00:59.030949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76c30486c443'
down_revision: Union[str, Sequence[str], None] = '0962dfbc80ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matching_history',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_jabatan', sa.String(length=255), nullable=False),
    sa.Column('total_kandidat', sa.Integer(), nullable=False),
    sa.Column('top_kandidat', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sub_tugas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('catatan_reviewer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matching_history')
    # ### end Alembic commands ###
