from app.core.config import settings


NEO4J_URI = settings.NEO4J_URI
NEO4J_USER = settings.NEO4J_USER
NEO4J_PASSWORD = settings.NEO4J_PASSWORD

MINIO_ENDPOINT = settings.MINIO_ENDPOINT
MINIO_ACCESS_KEY = settings.MINIO_ACCESS_KEY
MINIO_SECRET_KEY = settings.MINIO_SECRET_KEY
MINIO_BUCKET = settings.MINIO_BUCKET
MINIO_SECURE = settings.MINIO_SECURE

RAG_EMBEDDING_MODEL = settings.RAG_EMBEDDING_MODEL
RAG_EMBEDDING_DIMENSIONS = settings.RAG_EMBEDDING_DIMENSIONS
RAG_VECTOR_TOP_K = settings.RAG_VECTOR_TOP_K
RAG_GRAPH_LIMIT = settings.RAG_GRAPH_LIMIT